project-two/force-app/main/default/objects/Author__c.object
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project-two/force-app/main/default/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author</label>
        <referenceTo>Author__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

project-two/force-app/main/default/objects/Recommendation__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Recommendations</relationshipLabel>
        <relationshipName>Recommendations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                    <default>true</default>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review__c</fullName>
        <label>Review</label>
        <type>TextArea</type>
    </fields>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recommendation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project-two/force-app/main/default/classes/ProjectTwoBooksController.cls
public with sharing class ProjectTwoBooksController {
    
  @AuraEnabled
  public static List<Product2> getBooks() {
    return [SELECT Id, Name, Description
  			FROM Product2];
  }
    
  @AuraEnabled
  public static List<Product2> getBooksAndAuthor() {
    return [SELECT Name, Description, Author__r.Name
      FROM Product2];
  }
    
      @AuraEnabled
  public static List<Recommendation__c> getBookRecommendations() {
    return [SELECT Name, Review__c, Rating__c, Book__r.Name, Book__r.Author__r.Name
      FROM Recommendation__c
      WHERE Book__c != null];
  }
    
      @AuraEnabled
  public static List<Product2> getBooksWithoutAuthors(){
    return [SELECT Name
      FROM Product2
      WHERE Author__c = null];
  }
}