project-two/force-app/main/default/objects/Recommendation__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Recommendations</relationshipLabel>
        <relationshipName>Recommendations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recommendation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project-two/force-app/main/default/classes/recommendationcDuplicateCheck.cls
public class recommendationcDuplicateCheck {

    public static void recommendationcCheckBook(List<Recommendation__c> recommendationObjList){
        Set<String> setStr = new Set<String>();
//        List<Recommendation__c> recommendationcObj = new List<recommendation__c>();
        List<Recommendation__c> recommendationcList=[Select Book__c From Recommendation__c
                                                    WHERE OwnerId = :UserInfo.getUserId()];
    
        for(Recommendation__c d1:recommendationcList){
            setStr.add(d1.Book__c);
        	}
        
        for(Recommendation__c e1:recommendationObjList){
            if(setStr.contains(e1.Book__c)){
                e1.Book__c.addError('You may only submit one recommendation for each book.');
            }
        }
    }
}