Proj2/force-app/main/default/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Number_of_Reviews__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Reviews</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Review_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Review Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Proj2/force-app/main/default/objects/Recommendation__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Recommendations</relationshipLabel>
        <relationshipName>Recommendations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                    <default>true</default>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recommendation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Proj2/force-app/main/default/classes/ReviewTrackingHelper.cls
public class ReviewTrackingHelper {
    public static void reviewTracker(List<Recommendation__c> rev){
        
        List<Product2> ups = new List<Product2>();
        
        for (Recommendation__c r : rev){
            
            Product2 relRec = new Product2();
            relRec = r.Book__r;
        
        	relRec.Number_of_Reviews__c += 1;
        
        	relRec.Total_Review_Score__c += Integer.valueOf(r.Rating__c);
        
        	ups.add(relRec);
        }
        
         update ups;
        
        
        /*Product2 relRec = rev.Book__r;
        
        if(relRec.Number_of_Reviews__c == null){relRec.Number_of_Reviews__c = 1;}
        
        else relRec.Number_of_Reviews__c += 1;
        
        if(relRec.Total_Review_Score__c == null)relRec.Total_Review_Score__c = Integer.valueOf(rev.Rating__c);
        
        else relRec.Total_Review_Score__c += Integer.valueOf(rev.Rating__c);
        
        update relRec;*/
    }
}