Proj2/force-app/main/default/objects/Recommendation__c.object
<CustomObject>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                    <default>true</default>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Review Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Review__c</fullName>
        <label>Review</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>booknam__c</fullName>
        <formula>Book__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>booknam</label>
        <type>Text</type>
    </fields>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recommendation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Proj2/force-app/main/default/classes/reviewList.cls
public with sharing class reviewList {
    @AuraEnabled(cacheable=true)
    public static List<Recommendation__c> getReviewList() {
        return [
            SELECT Id, booknam__c, Rating__c, Review__c, Review_Date__c
            FROM Recommendation__c
            ORDER BY Review_Date__c
            LIMIT 10
        ];
    }
    @AuraEnabled
    public static void deleteRecord(Recommendation__c toDelete){
    delete toDelete;
}
}