Proj2/force-app/main/default/objects/Recommendation__c.object
<CustomObject>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                    <default>true</default>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recommendation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Proj2/force-app/main/default/classes/testReviewTrackingTrigger.cls
@isTest
public with sharing class testReviewTrackingTrigger {
    private static testMethod void testReviewTracker(){
        List<Recommendation__c> testRevList = new List<Recommendation__c>();
        Recommendation__c testRev;
        for(Integer i=0; i<5;i++){
            testRev = new Recommendation__c();
            switch on i{
                when 0{
                    testRev.Rating__c = '1';
                    break;
                }
                when 1{
                    testRev.Rating__c = '2';
                    break;
                }
                when 2{
                    testRev.Rating__c = '3';
                    break;
                }
                when 3{
                    testRev.Rating__c = '4';
                    break;
                }
                when 4{
                    testRev.Rating__c = '5';
                    break;
                }
            }            
            testRevList.add(testRev);
        }
        Test.startTest();
        insert testRevList;
        Test.stopTest();
    }
}